//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixErp302.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUrunAlisAlt
    {
        public int Id { get; set; }
        public string AlisGrupNo { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<int> BirimId { get; set; }
        public Nullable<decimal> AToplam { get; set; }
        public Nullable<decimal> Kdv { get; set; }
    
        public virtual bBirim bBirim { get; set; }
        public virtual tblUrunler tblUrunler { get; set; }
    }
}
