//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixErp302.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUrunSatisUst
    {
        public int Id { get; set; }
        public string SatisGrupNo { get; set; }
        public Nullable<int> CariId { get; set; }
        public Nullable<System.DateTime> ATarihdate { get; set; }
        public Nullable<int> Vade { get; set; }
        public Nullable<int> OdemeId { get; set; }
        public Nullable<decimal> AraToplam { get; set; }
        public Nullable<decimal> KdvToplam { get; set; }
        public Nullable<decimal> GenelToplam { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual bOdemeTurleri bOdemeTurleri { get; set; }
        public virtual TblCari TblCari { get; set; }
    }
}
