//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixErp302.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUrunAlisAltUst
    {
        public string AlisGrupNo { get; set; }
        public string CariAdi { get; set; }
        public Nullable<System.DateTime> ATarihdate { get; set; }
        public string FaturaNo { get; set; }
        public Nullable<int> Vade { get; set; }
        public string OdemeTipi { get; set; }
        public Nullable<decimal> AraToplam { get; set; }
        public Nullable<decimal> KdvToplam { get; set; }
        public Nullable<decimal> GenelToplam { get; set; }
        public Nullable<int> UrunId { get; set; }
        public string UrunAciklama { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
        public Nullable<int> Miktar { get; set; }
        public string BirimAdi { get; set; }
        public Nullable<decimal> AToplam { get; set; }
        public Nullable<decimal> Kdv { get; set; }
        public int Id { get; set; }
        public string UrunKodu { get; set; }
    }
}
